# Generated by Django 3.2.4 on 2021-07-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210728_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='item',
            new_name='title',
        ),
    ]
