# Generated by Django 3.2.4 on 2021-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_item_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Furniture'), ('c', 'Electronics'), ('d', 'Miscellaneous'), ('e', 'Kitchen'), ('f', 'None')], default='None', max_length=25),
        ),
    ]
